"""
4mulaQuery — Machine Learning Query Analytics Script
Author: Abdul Qadir

────────────────────────────────────────────────────────────
OVERVIEW
────────────────────────────────────────────────────────────
This script analyzes database query logs generated by the
4mulaQuery database engine and produces visual analytics
to help understand query patterns and performance.

The script performs the following tasks:

1. Reads query execution logs from:
       data/query_logs.csv

2. Performs statistical analysis on:
       • Query types
       • Execution times
       • Success/failure rates
       • Query timeline patterns

3. Generates analytics graphs and saves them to:
       assets/analytics/

4. Prints a summarized report in the terminal.

────────────────────────────────────────────────────────────
GENERATED OUTPUTS
────────────────────────────────────────────────────────────
The following analytics charts are produced:

1_query_distribution.png
    Distribution of query types (INSERT, SEARCH, DELETE, ALL)

2_execution_time.png
    Average execution time per query type

3_success_rate.png
    Success vs failed query percentage

4_timeline.png
    Execution timeline showing query flow over time

────────────────────────────────────────────────────────────
DEPENDENCIES
────────────────────────────────────────────────────────────
pandas
matplotlib

Install with:

pip install pandas matplotlib
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import os
import sys

# ─────────────────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────────────────
# Central configuration for file locations and UI styling.
# Keeping these values in one place makes the script easier
# to maintain and customize.

LOG_FILE    = "data/query_logs.csv"      # Input query log file
OUTPUT_DIR  = "assets/analytics"         # Folder for generated graphs

# Color palette used across all graphs
GOLD        = "#d4af37"
DARK        = "#0f1525"
TEXT        = "#c8d8f0"
SUCCESS     = "#2ecc71"
ERROR       = "#e74c3c"

# Graph color sequence
COLORS      = [GOLD, "#5ddf96", "#ff8c7f", "#6a9fd8"]

# ─────────────────────────────────────────────────────────
# SETUP FUNCTION
# ─────────────────────────────────────────────────────────
# Responsibilities:
#   1. Ensure output directory exists
#   2. Validate log file presence
#   3. Load CSV data into a pandas DataFrame
#   4. Convert timestamps into datetime format
#
# Returns:
#   pandas.DataFrame containing query logs

def setup():
    """Initializes analytics environment and loads query logs."""

    # Ensure analytics output directory exists
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Validate query log file existence
    if not os.path.exists(LOG_FILE):
        print(f"[ERROR] File nahi mili: {LOG_FILE}")
        print("Pehle queries run karo phir dobara chalao.")
        sys.exit(1)

    # Load CSV file into DataFrame
    df = pd.read_csv(LOG_FILE)

    # Convert timestamp column to datetime for analysis
    df["timestamp"] = pd.to_datetime(df["timestamp"])

    print(f"[OK] {len(df)} queries load hui\n")

    return df


# ─────────────────────────────────────────────────────────
# SUMMARY REPORT
# ─────────────────────────────────────────────────────────
# Prints a human-readable statistical overview of the
# query logs directly to the terminal.

def summary(df):
    """Displays a summary of query statistics in the terminal."""

    print("=" * 45)
    print("   4mulaQuery — Query Analytics Summary")
    print("=" * 45)

    print(f"  Total Queries    : {len(df)}")
    print(f"  Success Rate     : {df['success'].mean()*100:.1f}%")
    print(f"  Avg Exec Time    : {df['execution_ms'].mean():.1f} ms")
    print(f"  Fastest Query    : {df['execution_ms'].min()} ms")
    print(f"  Slowest Query    : {df['execution_ms'].max()} ms")

    print()
    print("  Query Type Breakdown:")

    # Count how many queries exist per type
    for qtype, count in df["type"].value_counts().items():
        pct = count / len(df) * 100
        print(f"    {qtype:<10} {count:>4} queries  ({pct:.1f}%)")

    print("=" * 45)
    print()


# ─────────────────────────────────────────────────────────
# QUERY DISTRIBUTION GRAPH
# ─────────────────────────────────────────────────────────
# Generates a bar chart showing how many queries were
# executed per command type.

def plot_query_distribution(df):
    """Creates a bar chart showing distribution of query types."""

    counts = df["type"].value_counts()

    fig, ax = plt.subplots(figsize=(8, 5))
    fig.patch.set_facecolor(DARK)
    ax.set_facecolor(DARK)

    bars = ax.bar(
        counts.index,
        counts.values,
        color=COLORS[:len(counts)],
        width=0.5,
        edgecolor="none"
    )

    # Display value labels above bars
    for bar in bars:
        ax.text(
            bar.get_x() + bar.get_width()/2,
            bar.get_height() + 0.3,
            str(int(bar.get_height())),
            ha="center",
            color=TEXT,
            fontsize=12,
            fontweight="bold"
        )

    ax.set_title("Query Type Distribution", color=GOLD, fontsize=15, fontweight="bold", pad=15)
    ax.set_xlabel("Query Type", color=TEXT, labelpad=10)
    ax.set_ylabel("Count", color=TEXT, labelpad=10)

    ax.tick_params(colors=TEXT)

    # Style graph borders
    for spine in ax.spines.values():
        spine.set_edgecolor("#1a2440")

    plt.tight_layout()

    path = f"{OUTPUT_DIR}/1_query_distribution.png"
    plt.savefig(path, dpi=150, bbox_inches="tight", facecolor=DARK)

    plt.close()

    print(f"[SAVED] {path}")


# ─────────────────────────────────────────────────────────
# EXECUTION TIME GRAPH
# ─────────────────────────────────────────────────────────
# Displays average execution time per query type.

def plot_execution_time(df):
    """Generates a bar chart for average execution time per query type."""

    avg_time = df.groupby("type")["execution_ms"].mean().sort_values(ascending=False)

    fig, ax = plt.subplots(figsize=(8, 5))
    fig.patch.set_facecolor(DARK)
    ax.set_facecolor(DARK)

    bars = ax.bar(
        avg_time.index,
        avg_time.values,
        color=COLORS[:len(avg_time)],
        width=0.5,
        edgecolor="none"
    )

    # Annotate bars with execution time
    for bar in bars:
        ax.text(
            bar.get_x() + bar.get_width()/2,
            bar.get_height() + 0.1,
            f"{bar.get_height():.1f}ms",
            ha="center",
            color=TEXT,
            fontsize=11,
            fontweight="bold"
        )

    ax.set_title("Avg Execution Time by Query Type", color=GOLD, fontsize=15, fontweight="bold", pad=15)
    ax.set_xlabel("Query Type", color=TEXT, labelpad=10)
    ax.set_ylabel("Avg Time (ms)", color=TEXT, labelpad=10)

    ax.tick_params(colors=TEXT)

    for spine in ax.spines.values():
        spine.set_edgecolor("#1a2440")

    plt.tight_layout()

    path = f"{OUTPUT_DIR}/2_execution_time.png"
    plt.savefig(path, dpi=150, bbox_inches="tight", facecolor=DARK)

    plt.close()

    print(f"[SAVED] {path}")


# ─────────────────────────────────────────────────────────
# SUCCESS RATE PIE CHART
# ─────────────────────────────────────────────────────────
# Visualizes the ratio of successful vs failed queries.

def plot_success_rate(df):
    """Creates a pie chart displaying success vs failure rate."""

    success_counts = df["success"].value_counts()

    labels  = ["Success" if k else "Failed" for k in success_counts.index]
    colors  = [SUCCESS if k else ERROR for k in success_counts.index]

    fig, ax = plt.subplots(figsize=(6, 6))
    fig.patch.set_facecolor(DARK)
    ax.set_facecolor(DARK)

    wedges, texts, autotexts = ax.pie(
        success_counts.values,
        labels=labels,
        colors=colors,
        autopct="%1.1f%%",
        startangle=90,
        wedgeprops={"edgecolor": DARK, "linewidth": 2}
    )

    for t in texts:
        t.set_color(TEXT)

    for t in autotexts:
        t.set_color(DARK)
        t.set_fontweight("bold")

    ax.set_title("Success vs Failed Queries", color=GOLD, fontsize=15, fontweight="bold", pad=15)

    plt.tight_layout()

    path = f"{OUTPUT_DIR}/3_success_rate.png"
    plt.savefig(path, dpi=150, bbox_inches="tight", facecolor=DARK)

    plt.close()

    print(f"[SAVED] {path}")


# ─────────────────────────────────────────────────────────
# QUERY TIMELINE GRAPH
# ─────────────────────────────────────────────────────────
# Displays how queries occur over time and their execution
# durations. Useful for identifying slow query spikes.

def plot_queries_over_time(df):
    """Creates a scatter + line chart representing query execution timeline."""

    df_sorted = df.sort_values("timestamp")
    df_sorted["query_num"] = range(1, len(df_sorted) + 1)

    fig, ax = plt.subplots(figsize=(10, 5))
    fig.patch.set_facecolor(DARK)
    ax.set_facecolor(DARK)

    # Plot queries by type
    for i, qtype in enumerate(df["type"].unique()):
        mask = df_sorted["type"] == qtype

        ax.scatter(
            df_sorted.loc[mask, "query_num"],
            df_sorted.loc[mask, "execution_ms"],
            color=COLORS[i % len(COLORS)],
            label=qtype,
            s=80,
            zorder=5
        )

    # Background trend line
    ax.plot(
        df_sorted["query_num"],
        df_sorted["execution_ms"],
        color=TEXT,
        alpha=0.3,
        linewidth=1,
        zorder=1
    )

    ax.set_title("Query Execution Timeline", color=GOLD, fontsize=15, fontweight="bold", pad=15)
    ax.set_xlabel("Query Number", color=TEXT, labelpad=10)
    ax.set_ylabel("Execution Time (ms)", color=TEXT, labelpad=10)

    ax.tick_params(colors=TEXT)

    for spine in ax.spines.values():
        spine.set_edgecolor("#1a2440")

    legend = ax.legend(facecolor=DARK, edgecolor=GOLD, labelcolor=TEXT)

    plt.tight_layout()

    path = f"{OUTPUT_DIR}/4_timeline.png"
    plt.savefig(path, dpi=150, bbox_inches="tight", facecolor=DARK)

    plt.close()

    print(f"[SAVED] {path}")


# ─────────────────────────────────────────────────────────
# MAIN EXECUTION PIPELINE
# ─────────────────────────────────────────────────────────
# Coordinates the full analytics workflow.

def main():
    df = setup()

    summary(df)

    plot_query_distribution(df)
    plot_execution_time(df)
    plot_success_rate(df)
    plot_queries_over_time(df)

    print(f"\n[DONE] Saare graphs → {OUTPUT_DIR}/")


# Entry point
if __name__ == "__main__":
    main()