package com.formulaquery.api;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * ------------------------------------------------------------
 * User Entity
 * ------------------------------------------------------------
 * Represents a registered user in the FormulaQuery system.
 *
 * Responsibilities:
 * - Store user information
 * - Handle authentication data
 * - Manage OTP verification
 * - Track account creation time
 *
 * Database Table: users
 * ------------------------------------------------------------
 */

@Entity
@Table(name = "users")
public class User {

    /**
     * Unique identifier for each user
     * Auto-generated by the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * Full name of the user
     */
    @Column(nullable = false)
    private String name;

    /**
     * User email address
     * Must be unique
     */
    @Column(unique = true, nullable = false)
    private String email;

    /**
     * User phone number
     * Optional field
     */
    private String phone;

    /**
     * Encrypted user password
     */
    @Column(nullable = false)
    private String password;

    /**
     * Indicates whether the user
     * has verified their email
     */
    private boolean isVerified = false;

    /**
     * One-Time Password used
     * for email verification
     */
    private String otp;

    /**
     * OTP expiration timestamp
     */
    private LocalDateTime otpExpiry;

    /**
     * Stores account creation time
     */
    private LocalDateTime createdAt = LocalDateTime.now();

    // ------------------------------------------------------------
    // Getters and Setters
    // ------------------------------------------------------------

    /**
     * Returns user ID
     */
    public int getId() {
        return id;
    }

    /**
     * Returns user name
     */
    public String getName() {
        return name;
    }

    /**
     * Updates user name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns user email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Updates user email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Returns user phone number
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Updates user phone number
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Returns encrypted password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Updates encrypted password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Returns verification status
     */
    public boolean isVerified() {
        return isVerified;
    }

    /**
     * Updates verification status
     */
    public void setVerified(boolean verified) {
        isVerified = verified;
    }

    /**
     * Returns OTP
     */
    public String getOtp() {
        return otp;
    }

    /**
     * Updates OTP
     */
    public void setOtp(String otp) {
        this.otp = otp;
    }

    /**
     * Returns OTP expiry time
     */
    public LocalDateTime getOtpExpiry() {
        return otpExpiry;
    }

    /**
     * Updates OTP expiry time
     */
    public void setOtpExpiry(LocalDateTime otpExpiry) {
        this.otpExpiry = otpExpiry;
    }

    /**
     * Returns account creation timestamp
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
}